#!/usr/bin/env python3
"""
Batch convert PNG sprites into a Lua palette table.

Input:
  - Reads every *.png in extras/sprites (or --input-dir)

Output:
  - Writes one Lua file (default extras/sprites/formatted_sprites.lua)
  - Structure:
      return {
        agumon = {
          sprite = { {0,1,1,...}, ... },
          color_palette = { [1] = 208, [2] = 130, ... }
        },
      }

Notes:
  - 0 in sprite rows means transparent.
  - Palette values are xterm-256 color indices.
  - When resizing, Image.NEAREST is used to preserve pixel edges.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from PIL import Image


Rgb = Tuple[int, int, int]


def build_xterm_palette() -> List[Rgb]:
    # Standard xterm 0-15 colors.
    base16: List[Rgb] = [
        (0, 0, 0),         # 0
        (128, 0, 0),       # 1
        (0, 128, 0),       # 2
        (128, 128, 0),     # 3
        (0, 0, 128),       # 4
        (128, 0, 128),     # 5
        (0, 128, 128),     # 6
        (192, 192, 192),   # 7
        (128, 128, 128),   # 8
        (255, 0, 0),       # 9
        (0, 255, 0),       # 10
        (255, 255, 0),     # 11
        (0, 0, 255),       # 12
        (255, 0, 255),     # 13
        (0, 255, 255),     # 14
        (255, 255, 255),   # 15
    ]

    palette: List[Rgb] = list(base16)

    # 16-231: 6x6x6 cube.
    levels = [0, 95, 135, 175, 215, 255]
    for r in levels:
        for g in levels:
            for b in levels:
                palette.append((r, g, b))

    # 232-255: grayscale ramp.
    for i in range(24):
        v = 8 + i * 10
        palette.append((v, v, v))

    return palette


XTERM_PALETTE = build_xterm_palette()


def nearest_xterm_index(rgb: Rgb) -> int:
    r, g, b = rgb
    best_i = 0
    best_d = None
    for i, (pr, pg, pb) in enumerate(XTERM_PALETTE):
        d = (r - pr) * (r - pr) + (g - pg) * (g - pg) + (b - pb) * (b - pb)
        if (best_d is None) or (d < best_d):
            best_d = d
            best_i = i
    return best_i


def sanitize_name(name: str) -> str:
    n = name.lower()
    n = re.sub(r"[^a-z0-9]+", "_", n).strip("_")
    if not n:
        n = "sprite"
    if n[0].isdigit():
        n = "_" + n
    return n


def resize_image(
    img: Image.Image,
    width: int | None,
    height: int | None,
) -> Image.Image:
    if width is None and height is None:
        return img

    src_w, src_h = img.size

    if width is not None and height is not None:
        target = (max(1, width), max(1, height))
    elif width is not None:
        ratio = width / src_w
        target = (max(1, width), max(1, int(round(src_h * ratio))))
    else:
        ratio = height / src_h
        target = (max(1, int(round(src_w * ratio))), max(1, height))

    return img.resize(target, Image.NEAREST)


def convert_image(
    path: Path,
    width: int | None,
    height: int | None,
    alpha_threshold: int,
) -> Tuple[List[List[int]], List[int], int, int]:
    img = Image.open(path).convert("RGBA")
    img = resize_image(img, width, height)
    w, h = img.size

    slot_by_xterm: Dict[int, int] = {}
    palette: List[int] = []
    rows: List[List[int]] = []

    for y in range(h):
        row: List[int] = []
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            if a <= alpha_threshold:
                row.append(0)
                continue

            xterm_index = nearest_xterm_index((r, g, b))
            slot = slot_by_xterm.get(xterm_index)
            if slot is None:
                slot = len(palette) + 1
                slot_by_xterm[xterm_index] = slot
                palette.append(xterm_index)
            row.append(slot)
        rows.append(row)

    return rows, palette, w, h


def format_sprite_rows(rows: Sequence[Sequence[int]], indent: str) -> List[str]:
    out = [f"{indent}sprite = {{"]
    for row in rows:
        line = ", ".join(str(v) for v in row)
        out.append(f"{indent}  {{{line}}},")
    out.append(f"{indent}}},")
    return out


def format_palette(palette: Sequence[int], indent: str) -> List[str]:
    out = [f"{indent}color_palette = {{"]
    for slot, color_index in enumerate(palette, start=1):
        out.append(f"{indent}  [{slot}] = {color_index},")
    out.append(f"{indent}}},")
    return out


def write_lua_output(
    output: Path,
    converted: List[Tuple[str, str, List[List[int]], List[int], int, int]],
) -> None:
    lines: List[str] = []
    lines.append("-- Auto-generated by extras/sprite_converter.py")
    lines.append("-- Do not edit manually; re-run the converter.")
    lines.append("return {")

    for key, source_name, rows, palette, w, h in converted:
        lines.append(f"  {key} = {{")
        lines.append(f'    source = "{source_name}",')
        lines.append(f"    width = {w},")
        lines.append(f"    height = {h},")
        lines.extend(format_sprite_rows(rows, "    "))
        lines.extend(format_palette(palette, "    "))
        lines.append("  },")

    lines.append("}")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def find_pngs(input_dir: Path) -> List[Path]:
    files = [p for p in input_dir.iterdir() if p.is_file() and p.suffix.lower() == ".png"]
    files.sort(key=lambda p: p.name.lower())
    return files


MULTI_RES_SIZES = [
    ("_sm", 8, 8),
    ("_md", 16, 16),
    ("", 32, 32),
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Batch convert PNG sprites to Lua palette tables")
    parser.add_argument(
        "--input-dir",
        default="extras/sprites",
        help="Directory containing PNG files (default: extras/sprites)",
    )
    parser.add_argument(
        "--output",
        default="extras/sprites/formatted_sprites.lua",
        help="Output Lua file (default: extras/sprites/formatted_sprites.lua)",
    )
    parser.add_argument(
        "--width",
        type=int,
        default=None,
        help="Resize to width (nearest-neighbor). Keeps aspect unless --height is also set.",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=None,
        help="Resize to height (nearest-neighbor). Keeps aspect unless --width is also set.",
    )
    parser.add_argument(
        "--alpha-threshold",
        type=int,
        default=0,
        help="Pixels with alpha <= threshold become transparent (default: 0)",
    )
    parser.add_argument(
        "--multi-res",
        action="store_true",
        default=False,
        help="Generate multiple resolutions per sprite (_sm 8x8, _md 16x16, base 32x32)",
    )

    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output = Path(args.output)

    if not input_dir.exists() or not input_dir.is_dir():
        print(f"Input directory does not exist: {input_dir}", file=sys.stderr)
        return 1

    pngs = find_pngs(input_dir)
    if not pngs:
        print(f"No PNG files found in {input_dir}", file=sys.stderr)
        return 1

    converted: List[Tuple[str, str, List[List[int]], List[int], int, int]] = []
    seen_keys = set()
    for path in pngs:
        base_key = sanitize_name(path.stem)
        base = base_key
        n = 2
        while base_key in seen_keys:
            base_key = f"{base}_{n}"
            n += 1

        if args.multi_res:
            for suffix, res_w, res_h in MULTI_RES_SIZES:
                key = f"{base_key}{suffix}"
                seen_keys.add(key)
                rows, palette, w, h = convert_image(path, res_w, res_h, args.alpha_threshold)
                converted.append((key, path.name, rows, palette, w, h))
                print(f"{path.name}: {w}x{h}, {len(palette)} palette entries -> key '{key}'")
        else:
            key = base_key
            seen_keys.add(key)
            rows, palette, w, h = convert_image(path, args.width, args.height, args.alpha_threshold)
            converted.append((key, path.name, rows, palette, w, h))
            print(f"{path.name}: {w}x{h}, {len(palette)} palette entries -> key '{key}'")

    write_lua_output(output, converted)
    print(f"Wrote {output} ({len(converted)} sprites)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
